version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
    volumes:
      - /home/radarr:/config
      - /mnt/plex/movies:/movies #optional
      - /mnt/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped