version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=PST
    volumes:
      - /home/radarr/config:/config
      - /home/plex/movies:/movies #optional
      - /home/deluge/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped