version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
    volumes:
      - /home/sonarr:/config
      - /mnt/plex/tv:/tv #optional
      - /mnt/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped